---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets available for the RDS DB Instance
      SubnetIds: !Ref 'Subnets'
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: mysql access
      VpcId: !Ref 'VPC'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          SourceSecurityGroupId: !Ref 'SecurityGroup'
      SecurityGroupEgress: []
      Tags:
        - Key: Name
          Value: !Sub 'mysql.${AWS::StackName}'
  DBPassword:
    Type: Custom::Secret
    Properties:
      Name: !Sub '/${AWS::StackName}/mysql/root/PGPASSWORD'
      Alphabet: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
      ReturnSecret: true
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-secret-provider'
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 30
      DBInstanceClass: db.t3.medium
      Engine: mysql
      EngineVersion: 5.7.28
      VPCSecurityGroups:
        - !Ref 'DatabaseSecurityGroup'
      DBName: root
      MasterUsername: root
      MasterUserPassword: !GetAtt 'DBPassword.Secret'
      MultiAZ: 'false'
      Port: '3306'
      PubliclyAccessible: 'false'
      DBSubnetGroupName: !Ref 'DBSubnetGroup'
      DBParameterGroupName: !Ref 'DatabaseParameterGroup'
    DeletionPolicy: Snapshot
  DatabaseParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: Parameters for MySQL
      Family: mysql5.7
      Parameters: {}

  KongPassword:
    Type: Custom::Secret
    Properties:
      Name: !Sub '/${AWS::StackName}/mysql/kong/PGPASSWORD'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-secret-provider'
  KongUser:
    Type: Custom::MySQLUser
    DependsOn:
      - Database
      - DBPassword
      - KongPassword
    Properties:
      User: kong
      PasswordParameterName: !Sub '/${AWS::StackName}/mysql/kong/PGPASSWORD'
      Database:
        User: root
        Host: !GetAtt 'Database.Endpoint.Address'
        Port: !GetAtt 'Database.Endpoint.Port'
        DBName: root
        PasswordParameterName: !Sub '/${AWS::StackName}/mysql/root/PGPASSWORD'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-mysql-user-provider-${VPC}'

  KongReaderPassword:
    Type: Custom::Secret
    Properties:
      Name: !Sub '/${AWS::StackName}/mysql/kongreader/PGPASSWORD'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-secret-provider'
  KongReaderUser:
    Type: Custom::MySQLUser
    DependsOn:
      - Database
      - DBPassword
      - KongReaderPassword
    Properties:
      User: kongreader
      WithDatabase: false
      PasswordParameterName: !Sub '/${AWS::StackName}/mysql/kongreader/PGPASSWORD'
      Database:
        User: root
        Host: !GetAtt 'Database.Endpoint.Address'
        Port: !GetAtt 'Database.Endpoint.Port'
        DBName: root
        PasswordParameterName: !Sub '/${AWS::StackName}/mysql/root/PGPASSWORD'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-mysql-user-provider-${VPC}'
  KongReaderUserGrant:
    Type: Custom::MySQLUserGrant
    DependsOn:
      - KongReaderUser
    Properties:
      Grant:
      - 'Select'
      'On': 'kong.*'
      User: kongreader
      Database:
        User: root
        Host: !GetAtt 'Database.Endpoint.Address'
        Port: !GetAtt 'Database.Endpoint.Port'
        DBName: root
        PasswordParameterName: !Sub '/${AWS::StackName}/mysql/root/PGPASSWORD'
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-mysql-user-provider-${VPC}'
